server:
  port: 8084

spring:
  application:
    name: match-service
  config:
    import: "classpath:shared-application.yaml"
  kafka:
    consumer:
      group-id: match-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:matches}?authSource=admin
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: DEBUG

springdoc:
  info:
    title: Tinder Cloud - Match Service
    description: Service that handles matches between user profiles on the Tinder cloud platform.
    version: 1.0.0
