name: 'Update GitOps Image Tag'
description: 'Updates Docker image tag in GitOps repository'
inputs:
  service-name:
    description: 'Service name to update'
    required: true
  deployment-file-path:
    description: 'Deployment file path in repo'
    required: true
  image-tag:
    description: "New image tag (e.g., v1.2.3 or sha)"
    required: true
  gitops-repo:
    description: 'GitOps repository'
    required: true
  gitops-token:
    description: 'GitHub token with write access to GitOps repo'
    required: true
  gitops-branch:
    description: 'Branch to update'
    required: false
    default: 'main'

runs:
  using: composite
  steps:
    - name: Checkout GitOps repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.gitops-repo }}
        token: ${{ inputs.gitops-token }}
        ref: ${{ inputs.gitops-branch }}
        path: gitops-repo

    - name: Update image tag
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/update.sh"
        "${{ github.action_path }}/update.sh" "${{ inputs.service-name }}" "${{ inputs.image-tag }}" "gitops-repo/${{ inputs.deployment-file-path }}"

    - name: Commit and push changes
      shell: bash
      working-directory: gitops-repo
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Update ${{ inputs.service-name }} image to ${{ inputs.image-tag }}"
        git push origin ${{ inputs.gitops-branch }}
