keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8088}
  realm: ${KEYCLOAK_REALM:tinder}
  admin-url: ${keycloak.base-url}${KEYCLOAK_ADMIN_PATH:/admin/realms/}${keycloak.realm}
  issuer-url: ${keycloak.base-url}${KEYCLOAK_ISSUER_PATH:/realms/}${keycloak.realm}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.issuer-url}${KEYCLOAK_JWK_PATH:/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
            redirect-uri: ${keycloak.base-url}${KEYCLOAK_REDIRECT_PATH:/login/oauth2/code/keycloak}
        provider:
          keycloak:
            issuer-uri: ${keycloak.issuer-url}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      properties:
        bootstrap.servers: {KAFKA_HOST:localhost:9093}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: io.github.wildblazz.shared.event.model

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

kafka:
  default-partitions: 2
  partitions:
    profile-delete-event: 3
