server:
  port: 8085

spring:
  application:
    name: recommendation-service
  config:
    import: "classpath:shared-application.yaml"
  kafka:
    consumer:
      group-id: recommendation-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:recommendation}?authSource=admin
      auto-index-creation: true

springdoc:
  info:
    title: Tinder Cloud - Recommendation Service
    description: Service for preparing recommendations to the users in Tinder Cloud platform
    version: 1.0.0

recommendation:
  batch-generate:
    cron: "0 0 * * * *" # every hour
