server:
  port: 8082

spring:
  application:
    name: profile-service
  config:
    import: "classpath:shared-application.yaml"
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/profiles}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

# MinIO configuration
minio:
  endpoint: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: profile-photos

springdoc:
  info:
    title: Tinder Cloud - Profile Service
    description: REST API for managing user profiles in Tinder Cloud platform
    version: 1.0.0
